import pandas as pd

# Data for the column mapping
column_mapping_data = {
    "old_name": [
        "Response date",
        "What is your age category?",
        "What is your gender?",
        "What Rowing Club are you primarily affiliated with?",
        "Are you a school student? If yes, which school do you attend?",
        "Did you participate in any regattas in 2025?",
        "Training",
        "Regattas and Racing",
        "Physical Health Benefits",
        "Mental Health Benefits",
        "Social and Community Aspect",
        "Rowing Culture",
        "Did you compete in any Pennant regattas this season?",
        "If you did not attend all regattas, why?",
        "Other (please provide details here)",
        "What grade were you in this season?",
        "The current grading system accurately adjusts my rowing score to support enjoyable and meaningful racing?",
        "What event grades did you compete in this season?",
        "On average, how many events per Pennant regatta did you compete in?",
        "How many events would you prefer to compete in per regatta?",
        "The seat fee cap for the Pennant regattas enabled me to enter more events?",
        "The cost of entering events has prevented me from racing in as many events per day as I would have liked?",
        "The program limited my ability to race in as many events per day as I would have liked?",
        "Time constraints limited the number of events I could race in per day?",
        "Focusing on certain events impacted my ability to race in the number of events per day that I would have preferred?",
        "Influence from my Club or Coach affected the number of events I raced in per day?",
        "I support the addition of the Open Non-Pennant Single Scull event to the program?",
        "I support the addition of the D-Grade Double Scull event to the sweep regatta program?",
        "More age-based small boat events should be considered for future programs?",
        "I support the addition of the Masters 4- and 4x events to the program?",
        "What would be your preferred frequency for holding Pennant regattas?",
        "The 2025 Pennant regatta season provided a better racing experience than the 2024 season?",
        "I agree that we should only award 1st place medals at the State Championships and Pennant regattas?",
        "Do you have any additional feedback or suggestions for improvement regarding the Pennant season or the State Championships?",
        "Did you compete in any Head Race regattas this season?",
        "Which Head Races did you compete in this season?",
        "I rate my overall experience at Head Race regattas this season as positive?",
        "I am satisfied with the timing of Head Race events within the season schedule?",
        "What aspects of the Head Race regattas would you like to see improved in the future?",
        "Did you compete in any Masters regattas this season?",
        "Which Masters regattas did you participate in this season?",
        "On average, how many events per Masters regatta did you compete in?",
        "How many events would you prefer to compete in per Masters regatta?",
        "The Masters regatta program did not allow me to race in as many events per day as I would have liked?",
        "Are you aware that as a Masters athlete, you can enter the Masters 4- or 4x events at Pennant regattas, along with racing opportunities in all other boat classes at C or D Grade, and that these races are all over 1,000m?",
        "Having additional racing opportunities, such as the Masters 4- and 4x events and other grade boat classes over 1,000m, would make me more likely to enter a Pennant Regatta?",
        "I prefer Canning Bridge as a racing location for future Masters regattas?",
        "I prefer Champion Lakes as a racing location for future Masters regattas?",
        "Do you have any feedback regarding the Masters racing locations this season (Champion Lakes)?",
        "What would be your preferred frequency for holding Masters regattas?",
        "The 2025 Masters regatta season provided a better racing experience than the 2024 season?",
        "I agree that we should only award 1st place medals at Masters regattas?",
        "We are considering extending the Masters regatta season by offering additional regattas and/or adding additional Masters events to existing regattas. What change would you most like to see?",
        "Do you have any additional feedback or suggestions for improvement regarding the Masters season or the Masters State Championships?",
        "Did you compete in any All Schools regattas this season?",
        "What school year did you primarily compete in this season?",
        "On average, how many events per All Schools regatta did you compete in?",
        "How many events would you prefer to compete in per All Schools regatta?",
        "The All Schools regatta program did not allow me to race in as many events per day as I would have liked?",
        "Did you compete at the All Schools State Championships?",
        "I feel that the length of the All Schools State Championships on a one day program is too long a day?",
        "I agree that seeding crews for the All Schools State Championships (based on their results from lead-up regattas and self-ranking) helped to facilitate a fair All Schools State Championships?",
        "I would support the idea of running the All Schools State Championships over two days (heats and finals format) to allow the format to utilise Heats and Finals again?",
        "What would be your preferred frequency for holding All Schools regattas?",
        "I support moving Year 9 events from 500m to 1000m?",
        "I support extending more Open events to a distance of 1,500m?",
        "The 2025 All Schools regatta season provided a better racing experience than the 2024 season?",
        "I agree that we should award 1st place medals for every race at the three (non-Championship) All Schools regattas?",
        "Do you have any additional feedback or suggestions for improvement regarding the All-Schools season or the All Schools State Championships?",
        "Do you consider yourself to be a Non-Competitive rower?",
        "I prefer recreational rowing over competitive rowing because the time commitment for competitions feels too demanding?",
        "My current skill level or experience makes me more comfortable focusing on recreational rowing rather than competing?",
        "The cost of participating in competitive events is a significant reason why I choose recreational rowing?",
        "I enjoy the social and non-competitive aspects of recreational rowing, which makes me less interested in racing?",
        "More support or guidance for recreational rowers transitioning to competition would make me more likely to consider competitive rowing?",
        "What factors or support would make you more likely to consider participating in competitive rowing events?",
        "Which of the following changes would make you more likely to start cometiting in competitive racing events?",
        "Which of the following factors have influenced your decision to not participate in competitive rowing events?",
        "Rowing offers good value compared to other sports in Western Australia, considering factors like cost, facilities, and opportunities?",
        "Would you be interested in participating in Coastal Beach Sprints during the summer?",
        "Please provide any additional information or suggestions you would like Rowing WA to consider when developing the 2026 regatta program?",
        "Promotion and governance of the sport of Rowing in Western Australia",
        "Making rowing accessible to as many Western Australians as practicable",
        "Delivering a positive rowing experience",
        "Providing and facilitating high performance pathways",
        "Thank you for completing this survey. We are running a competition for a $250 Visa Card, do you wish to be entered in the draw?",
    ],
    "new_name": [
        "response_date",
        "age_category",
        "gender",
        "club_affiliation",
        "school_student",
        "participated_in_regattas_2025",
        "rating_training",
        "rating_regattas_racing",
        "rating_physical_health",
        "rating_mental_health",
        "rating_social_community",
        "rating_rowing_culture",
        "competed_pennant",
        "reason_missed_regattas",
        "reason_missed_regattas_other",
        "grade_this_season",
        "satisfaction_grading_system",
        "event_grades_competed",
        "avg_events_per_pennant",
        "preferred_events_per_regatta",
        "seat_fee_cap_impact",
        "cost_prevented_racing",
        "program_limited_racing",
        "time_constraints_limited_racing",
        "focus_on_events_impact",
        "club_coach_influence",
        "support_open_non_pennant_single",
        "support_d_grade_double_scull",
        "support_age_based_small_boat_events",
        "support_masters_4_and_4x",
        "preferred_pennant_frequency",
        "pennant_2025_vs_2024_experience",
        "support_1st_place_medals_only",
        "feedback_pennant_championships",
        "competed_head_race",
        "head_races_competed",
        "head_race_experience_rating",
        "satisfaction_head_race_timing",
        "improvements_head_races",
        "competed_masters_regattas",
        "masters_regattas_participated",
        "avg_events_per_masters_regatta",
        "preferred_events_per_masters_regatta",
        "masters_program_limited_racing",
        "awareness_masters_pennant_opportunities",
        "masters_pennant_opportunities_likelihood",
        "prefer_canning_bridge_masters",
        "prefer_champion_lakes_masters",
        "feedback_masters_locations",
        "preferred_masters_frequency",
        "masters_2025_vs_2024_experience",
        "support_1st_place_medals_masters",
        "desired_masters_season_extension",
        "feedback_masters_season_championships",
        "competed_all_schools_regattas",
        "school_year_competed",
        "avg_events_per_all_schools_regatta",
        "preferred_events_per_all_schools_regatta",
        "all_schools_program_limited_racing",
        "competed_all_schools_championships",
        "all_schools_championships_length_too_long",
        "support_all_schools_seeding",
        "support_all_schools_2_day_championships",
        "preferred_all_schools_frequency",
        "support_year_9_1000m",
        "support_open_1500m",
        "all_schools_2025_vs_2024_experience",
        "support_all_schools_medals_every_race",
        "feedback_all_schools_season_championships",
        "is_non_competitive_rower",
        "reason_recreational_time_commitment",
        "reason_recreational_skill_level",
        "reason_recreational_cost",
        "reason_recreational_social_aspect",
        "support_transition_to_competitive",
        "factors_to_consider_competitive",
        "changes_to_start_competing",
        "factors_not_competing",
        "rowing_value_vs_other_sports",
        "interest_in_coastal_beach_sprints",
        "feedback_2026_regatta_program",
        "rating_promotion_governance",
        "rating_accessibility",
        "rating_positive_experience",
        "rating_high_performance_pathways",
        "enter_competition",
    ],
    "recommended_type": [
        "datetime64[ns]",
        "category",
        "category",
        "category",
        "object",
        "category",
        "int8",
        "int8",
        "int8",
        "int8",
        "int8",
        "int8",
        "category",
        "object",
        "object",
        "category",
        "Int8",
        "object",
        "float64",
        "float64",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "category",
        "Int8",
        "Int8",
        "object",
        "category",
        "object",
        "Int8",
        "Int8",
        "object",
        "category",
        "object",
        "float64",
        "float64",
        "Int8",
        "category",
        "Int8",
        "Int8",
        "Int8",
        "object",
        "category",
        "Int8",
        "Int8",
        "category",
        "object",
        "category",
        "object",
        "object",
        "object",
        "Int8",
        "category",
        "Int8",
        "Int8",
        "Int8",
        "category",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "object",
        "category",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "Int8",
        "object",
        "object",
        "object",
        "Int8",
        "category",
        "object",
        "int8",
        "int8",
        "int8",
        "int8",
        "category",
    ],
    "variable_type": [
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "dependent",
        "dependent",
        "dependent",
        "dependent",
        "dependent",
        "dependent",
        "independent",
        "independent",
        "independent",
        "independent",
        "dependent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "dependent",
        "independent",
        "independent",
        "independent",
        "independent",
        "dependent",
        "dependent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "dependent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "dependent",
        "independent",
        "independent",
        "dependent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "independent",
        "dependent",
        "dependent",
        "independent",
        "dependent",
        "dependent",
        "dependent",
        "dependent",
        "independent",
    ],
}

# Create a DataFrame
df = pd.DataFrame(column_mapping_data)

# Define the file path for the Excel file
file_path = "column_mapping.xlsx"

# Write the DataFrame to an Excel file
df.to_excel(file_path, index=False)

print(f"Column mapping has been saved to '{file_path}'")
